FROM adminer:latest

LABEL maintainer="Hendro Wibowo <hendrothemail@gmail.com>"

# Add volume for sessions to allow session persistence
VOLUME /sessions

USER adminer

# We expose Adminer on port 8080 (Adminer's default)
EXPOSE 8080
