services:
  worker:
    build: ../../apps/worker
    command: celery -A main worker --loglevel=info --logfile=logs/workers.log
    volumes:
      - ../../apps/worker:/code/worker
    ports:
      - "8888:8888"
    restart: unless-stopped
    environment:
      - API_BASE_URL=${API_BASE_URL}
      - DEXSCREENER_API=${DEXSCREENER_API}
      - COINGECKO_API=${COINGECKO_API}
      - COINGECKO_API_KEY=${COINGECKO_API_KEY}
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD:-cryptoredis}@${REDIS_HOST}:${REDIS_PORT}/0
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD:-cryptoredis}@${REDIS_HOST}:${REDIS_PORT}/0
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=0
      - SYSTEM_PROMPT=${SYSTEM_PROMPT}
      - LLM_API_KEY=${OPENROUTER_API_KEY}
      - LLM_BASE_URL=${OPENROUTER_API_URL}
      - MODEL_NAME=${OPENROUTER_MODEL_NAME}
      - ADAPTER_CLASS=${ADAPTER_CLASS}
      - LLM_COMPLETION_RETRY_LIMIT=${LLM_COMPLETION_RETRY_LIMIT:-3}
      - WEB3_PLATFORM=${WEB3_PLATFORM}
      - WEB3_PROVIDER_URL=${WEB3_PROVIDER_URL}
      - WEB3_CHAIN_ID=${WEB3_CHAIN_ID}
      - WEB3_WALLET_ADDRESS=${WEB3_WALLET_ADDRESS}
      - WEB3_WALLET_PRIVATE_KEY=${WEB3_WALLET_PRIVATE_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - api
      - redis
    networks:
      - backend
